Remove agnoster theme due to git error
The error was:
error: Server does not allow request for unadvertised object

Possibly the commit which was referenced was force pushed away?
Or a server setting prevents retrieval of that commit?